# Generated by Django 3.2.8 on 2021-10-11 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('votes', models.IntegerField(default=0, verbose_name='Votes')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Restaurant')),
            ],
        ),
    ]
